# Generated by Django 5.1.3 on 2024-11-10 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_rename_task_tasks"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tasks",
            new_name="Task",
        ),
    ]
