# Generated by Django 5.1.3 on 2024-11-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_metrics"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Metrics",
            new_name="Metric",
        ),
    ]
