# Generated by Django 5.1.3 on 2024-11-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_rename_metrics_metric"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="average_cycle_time",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
