# Generated by Django 5.1.3 on 2024-11-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_metric_average_cycle_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metric",
            name="average_cycle_time",
        ),
        migrations.AddField(
            model_name="metric",
            name="name",
            field=models.CharField(default="test", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="metric",
            name="value",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
