# Generated by Django 5.1.3 on 2024-11-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_remove_metric_average_cycle_time_metric_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="name",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
