# Generated by Django 5.1.3 on 2024-11-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_alter_metric_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metric",
            name="name",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
